//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prova.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passagem
    {
        public int id { get; set; }
        public string nome_passageiro { get; set; }
        public System.DateTime data_passagem { get; set; }
        public string classe { get; set; }
        public string cidade_origem { get; set; }
        public string cidade_destino { get; set; }
        public System.TimeSpan hora_voo { get; set; }
    }
}
